### ISSUE TITLE
prone.AllowedJobs

### ISSUE THREAD

**Issue by GrGrMichi** [gspetrou/Prone-Mod#3]
The config option prone.AllowedJobs don't works for me. 
I want to blacklist a job, so the job can't prone. I used the exact name from F4 and I tried all varations:
I tried to set prone.RestrictByJob and prone.JobsIsBlacklist on true, prone.AllowAllProne, prone.RestrictByJob and prone.JobsIsBlacklist on true and all things standalone and so on...
In none case it worked. I think this config option is completely not working. If it is then tell me please what Iam doing wrong. If not...pls fix

**Comment by gspetrou** [comment]
In the update I am about to put out I changed this to use the TEAM_ enums, this should fix the issue and not conflict with any custom F4 menus.

**Comment by GrGrMichi** [comment]
still not working for me

**Comment by gspetrou** [comment]
Haha nearly a year later! Ill take another look tomorrow, what gamemode exactly are you running? Ill be testing on completely vanilla DarkRP (whatever the newest version is).

**Comment by GrGrMichi** [comment]
I can't even remember opening this ticket. I was about to open a new one but then I discovered this one xD I'm also using the latest DarkRP version
