### ISSUE TITLE
'prone' table reference is shared among all players

### ISSUE THREAD

**Issue by wyozi** [gspetrou/Prone-Mod#6]
```lua
-- sh_prone.lua
local PLAYER = FindMetaTable("Player")
PLAYER.prone = {}
```

Sharing the table makes it so only one player can prone up/down at a time and probably other funky errors.

**Comment by gspetrou** [comment]
Damn, I had no idea that was the case. Will look into this a bit then most likely create the table on the player on their initial spawn. Thanks!
